import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import React from "react";
import ReactPlayer from 'react-player'

const Id = (props) => {
  const router = useRouter()
  //const { title } = router.query
  const myfav=(event)=>{
   console.log("myfav",event.target.value);
    // const existingEntries=[]
    const existingEntries =  JSON.parse(localStorage.getItem("myfav"));

    //if(existingEntries == null) existingEntries = [];
    //console.log("myfav",JSON.parse(event.target.value));
    existingEntries.push(JSON.parse(event.target.value));
    localStorage.setItem("myfav", JSON.stringify(existingEntries))
  };
  const getDetails=(event)=>{
    //localStorage.setItem("myfav", JSON.stringify(item))
    //https://imdb-api.com/en/API/Title/k_aeld87p6/tt1375666/FullActor,FullCast,Posters,Images,Trailer,Ratings,

  };

  return ( 
    <div className="container">
      <Head>
        <title>Movie Time</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row pt-1 pb-1">
        <div className="col-lg-12 text-center">
               <h3 className="py-3">Movie Time</h3>
            <h4 className="text-center">Find the best movie</h4>
        </div>
      </div>

      <div className="search-sec">
        <div className="container">
                  <Form/>

        </div>
      </div>
       

  
   
    <div className="container">
        <div className="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5">

        <div className="col-10">
          <div className="card" >
          <div className="card-title">
          {props.sources.trailer && (
                <ReactPlayer url={props.sources.trailer.linkEmbed} />
          )}

          </div>

            
          </div>
          <div className="card-body">
              <h2 className="card-titles">{props.sources.fullTitle}</h2>
              <p><b>Rating:</b>{props.sources.ratings.imDb}</p>
              <p><b>Duration</b>: {props.sources.runtimeStr}</p>
              <p><b>Plot:</b> {props.sources.plot}</p>
              <p><b>Directors:</b> {props.sources.directors}</p>
              <p><b>Stars:</b>{props.sources.stars}</p>
              <p><b>writers</b>:{props.sources.trailer.linkEmbed}</p>

              
            </div>

        </div>

        </div>
       
    </div>
    <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
          </span>
        </a>
      </footer>
    </div>
    )
}

Id.getInitialProps = async function(context) {
  const { id } = context.query
  console.log("false",id);
  const res = await fetch("https://imdb-api.com/en/API/Title/k_s25b120r/"+id+"/FullActor,FullCast,Posters,Images,Trailer,Ratings,")
  //const res = await fetch('https://api.tvmaze.com/search/sources?q=batman')
  //const res = await fetch('https://randomuser.me/api/?results=10')
  //const res = await fetch ('https://newsapi.org/v2/top-headlines?country=us')
  const data = await res.json()

  console.log('source data fetched. Count: ',data);

  return {
    sources: data//.map(entry => entry.source)
  }
}
const Form = () => {
  const [state, setState] = React.useState({
    title: "",
  });

  function handleChange(e) {
    setState({ ...state, [e.target.name]: e.target.value });
  }
  async function handleSubmit(e) {
    e.preventDefault();

    let formData = new FormData();
          console.log("formData", formData);

      for (let [key, value] of Object.entries(state)) {
        console.log(key, value);
        window.location.href = "/movie/"+value;      
      }
  }

  return (
    <form onSubmit={handleSubmit}>
    <div className="row justify-content-md-center">
      <div className="col-lg-12">
          <div className="row justify-content-md-center">
              <div className="col-lg-4 col-md-4 col-sm-12 p-0">

                  <input
                    name="title"
                    type="text"
                    placeholder="Enter movie name"
                    onChange={handleChange}
                    value={state.title}
                    required
                  />
                  
                  <input
                    name="bot-field"
                    type="text"
                    onChange={handleChange}
                    style={{ display: "none" }}
                  />
                  <button type="submit">Search Movie</button>
                  </div>
                </div>
            </div>
        </div>
    </form>
  );
}
export default Id