import Head from 'next/head'
import Image from 'next/image'
import React from "react";
import Router from "next/router";

import styles from '../styles/Home.module.css'


import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
  
export default function Home(props ) {
  const myfav=(event)=>{
     console.log("myfav",event.target.value);

  const existingEntries = JSON.parse(localStorage.getItem("myfav")) ? JSON.parse(localStorage.getItem("myfav")) : []

    //if(existingEntries == null) existingEntries = [];
    //console.log("myfav",JSON.parse(event.target.value));
    existingEntries.push(JSON.parse(event.target.value));
    localStorage.setItem("myfav", JSON.stringify(existingEntries))
    toast("Movie added to your watch list")
  };
  const getDetails=(event)=>{
    const movieID= event.target.value;
    window.location.href = "/details/"+movieID;

    //localStorage.setItem("myfav", JSON.stringify(item))
    //https://imdb-api.com/en/API/Title/k_aeld87p6/tt1375666/FullActor,FullCast,Posters,Images,Trailer,Ratings,

  };

  return (     

    <div className="container">
      <Head>
        <title>Movie Time</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer />

      <div className="row pt-1 pb-1">
        <div className="col-lg-12 text-center">
               <h3 className="py-3">Movie Time</h3>
            <h4 className="text-center">Find the best movie</h4>
        </div>
      </div>

      <div className="search-sec">
        <div className="container">
          <Form/>
        </div>
         <a
          href="/mylist"
          target="_blank"
          rel="noopener noreferrer"
          className="btn btn-success"
        >
          My List
        </a>
      </div>
       

  
   
    <div className="container">
        <div className="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5">

       {props.movies.items.map((item) => (
        <div className="col-4" key={item.id}>
          <div className="card" >
            <div className="card-title">
              <Image className="card-img-top" alt="300x200" layout='fill' src={item.image}/>
            </div>            
          </div>
          <div className="card-body">
              <h2 className="card-titles">{item.title}</h2>
              <p>{item.description}</p>
            </div>
          <button className="btn" value={item.id} onClick={getDetails}>Details</button>
          <button className="btn" value={JSON.stringify(item)} key={item} onClick={myfav}>My List</button>

        </div>

        ))}
        </div>
       
    </div>
    <footer className={styles.footer}>
        
          Powered by{' '}
          <span className={styles.logo}>
          </span>
      </footer>
    </div>
  );

}
export const getStaticProps = async (context) => {
  const res = await fetch("https://imdb-api.com/en/API/MostPopularMovies/k_s25b120r");
  const movies = await res.json();
   if(!movies) {
    return {
      redirect: {
        permanent: false,
        destination: '/somewhere-else'
      }
    }
  }
  //console.log('movies',movies);
  return {
    props: {
      movies,
    },
  };
};



const Form = () => {
  const [state, setState] = React.useState({
    title: "",
  });

  function handleChange(e) {
    setState({ ...state, [e.target.name]: e.target.value });
  }
  async function handleSubmit(e) {
    e.preventDefault();

    let formData = new FormData();
          console.log("formData", formData);

    for (let [key, value] of Object.entries(state)) {
      console.log(key, value);
      //formData.append(key, value);
        window.location.href = "/movie/"+value;
      }
   }

  return (
    <form onSubmit={handleSubmit}>
    <div className="row justify-content-md-center">
      <div className="col-lg-12">
          <div className="row justify-content-md-center">
              <div className="form-group col-lg-4 col-md-4 col-sm-12 p-0">

                  <input
                    name="title"
                    className="form-control"
                    type="text"
                    placeholder="Enter movie name"
                    onChange={handleChange}
                    value={state.title}
                    required
                  />
                  
                  <input
                    name="bot-field"
                    type="text"
                    onChange={handleChange}
                    style={{ display: "none" }}
                  />
                  <button type="submit" className="btn btn-primary">Search Movie</button>
                  </div>
                </div>
            </div>
        </div>
    </form>
  );
}