import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from "react";

export default class Mylist extends React.Component{
  //const title  = localStorage.getItem("myfav")
  state = {
    movies: []
  };

  // static async getInitialProps(props) {
  //   const { query } = props;
  //   var mymov = localStorage.getItem('myfav');
  //       console.log("Cleint side",mymov);

  //   return {
  //     movies: mymov,
  //   };
  // }
   static async getInitialProps(props) {
    const { query } = props;
        console.log("Cleint side--",query);
    return { query }
  }
  componentDidMount(){
    const  movies  = JSON.parse(localStorage.getItem("myfav"));
        console.log("Cleint side...",movies);
        //console.log(JSON.parse(title));
        this.setState({
          movies
        })

  } 

  render()
   {
        const { movies = [] } = this.state;
        console.log(movies);
    return (
      <div className="container">
      <Head>
        <title>Movie Time</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row pt-1 pb-1">
        <div className="col-lg-12 text-center">
               <h3 className="py-3">Movie Time</h3>
            <h4 className="text-center">Find the best movie</h4>
        </div>
      </div>

      <div className="container">
        <div className="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5">

          {movies.map(u =>

           <div className="col-4" key={u.id}>
            <div className="card" >
              <div className="card-title">
                <Image className="card-img-top" alt="300x200" layout='fill' src={u.image}/>
              </div>
      
             </div>
           
           <div className="card-body">
              <h2 className="card-titles">{u.title}</h2>
              <p>{u.description}{u.fullTitle}</p>
            </div>

        </div>



           )}
        </div>
      </div>
      </div>
    );
      
  }
}

/*Mylist.getInitialProps = async () => {
if (typeof window !== 'undefined') {
    localStorage.setItem('username', 'Joe Smith');
    console.log('Rendering on browser or client')
} else {
    console.log('Rendering on server');
}
  const token =[];// JSON.parse(localStorage.getItem('myfav'));
  
  return { page: token };
}*/
const Form = () => {
  const [state, setState] = React.useState({
    title: "",
  });

  function handleChange(e) {
    setState({ ...state, [e.target.name]: e.target.value });
  }
  async function handleSubmit(e) {
    e.preventDefault();

    let formData = new FormData();
          console.log("formData", formData);

      for (let [key, value] of Object.entries(state)) {
        console.log(key, value);
        window.location.href = "/movie/"+value;      
      }
  }

  return (
    <form onSubmit={handleSubmit}>
    <div className="row justify-content-md-center">
      <div className="col-lg-12">
          <div className="row justify-content-md-center">
              <div className="col-lg-4 col-md-4 col-sm-12 p-0">

                  <input
                    name="title"
                    type="text"
                    placeholder="Enter movie name"
                    onChange={handleChange}
                    value={state.title}
                    required
                  />
                  
                  <input
                    name="bot-field"
                    type="text"
                    onChange={handleChange}
                    style={{ display: "none" }}
                  />
                  <button type="submit">Search Movie</button>
                  </div>
                </div>
            </div>
        </div>
    </form>
  );
}
